use dbUCF ;  

/*----------------------------------------------------------------------------------------------------------------------------------*/
/*--------------------------------------------- Declare Hash Function --------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
DELIMITER $$
DROP FUNCTION IF EXISTS randHash; 
CREATE FUNCTION randHash(nTimes INT) RETURNS VARCHAR(200)
    BEGIN
        DECLARE myVariable VARCHAR(200);
        DECLARE x INT;
        SET x = 1;
        SET myVariable = substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand(@seed:=round(rand(rand()*100)*4294967296))*36+1, 1);

        REPEAT
            SET myVariable=concat(substring('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', rand(@seed:=round(rand(rand()*100)*4294967296))*36-1, 1), myVariable);
            SET  x = x + 1; 

        UNTIL x  > nTimes
        END REPEAT;
        RETURN myVariable ;
    END$$
DELIMITER ;



/*----------------------------------------------------------------------------------------------------------------------------------*/
/*--------------------------------------------- Declare Usage Record Procedure ------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
DELIMITER $$
DROP PROCEDURE IF EXISTS UsageRecLoop$$
CREATE PROCEDURE UsageRecLoop(nTimes INT)
    BEGIN
        DECLARE x INT;
        SET x = 1;

        REPEAT
        
            INSERT INTO Usage_Record( student_id, resource_id, usage_date)
            VALUES  ((SELECT student_id FROM Student ORDER BY RAND() LIMIT 1), (SELECT resource_id FROM Resource ORDER BY RAND() LIMIT 1), FROM_UNIXTIME(UNIX_TIMESTAMP('2014-11-30 14:53:27') + FLOOR(0 + (RAND() * 2542000))));

            SET  x = x + 1; 

    UNTIL x  > nTimes
    END REPEAT;
END$$
DELIMITER ;









/*----------------------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------- INSERT Student DATA -----------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
INSERT INTO Student(student_id, first_name, last_name) 
  VALUES (randHash(8),'Benjamin','Greene'),
        (randHash(8),'Douglas','Ortiz'),
        (randHash(8),'Rhoda','Foster'),
        (randHash(8),'Walter','Carr'),
        (randHash(8),'Etta','Hardy'),
        (randHash(8),'William','Copeland'),
        (randHash(8),'Charles','Rodgers'),
        (randHash(8),'Elizabeth','Jones'),
        (randHash(8),'Vera','Waters'),
        (randHash(8),'Connor','French'),
        (randHash(8),'Elmer','Stokes'),
        (randHash(8),'Gilbert','Murphy'),
        (randHash(8),'Garrett','Flores'),
        (randHash(8),'Bill','Page'),
        (randHash(8),'Aiden','Copeland'),
        (randHash(8),'Troy','Stephens'),
        (randHash(8),'Elizabeth','Cohen'),
        (randHash(8),'Jonathan','Wallace'),
        (randHash(8),'Ora','McCarthy'),
        (randHash(8),'Luis','Allen'),
        (randHash(8),'Celia','Simmons'),
        (randHash(8),'Stephen','Graves'),
        (randHash(8),'Roy','Rhodes'),
        (randHash(8),'Ethel','Howell'),
        (randHash(8),'Lily','Thomas'),
        (randHash(8),'John','Manning'),
        (randHash(8),'Esther','Robbins'),
        (randHash(8),'Mabelle','Martin'),
        (randHash(8),'Jesse','Henry'),
        (randHash(8),'Ethel','Hardy'),
        (randHash(8),'Michael','Strickland'),
        (randHash(8),'Phoebe','Nunez'),
        (randHash(8),'Winifred','Caldwell'),
        (randHash(8),'Gussie','Hicks'),
        (randHash(8),'Cordelia','Payne'),
        (randHash(8),'Alvin','Burke'),
        (randHash(8),'Nathaniel','Cummings'),
        (randHash(8),'Luis','Morrison'),
        (randHash(8),'Antonio','Norton'),
        (randHash(8),'Justin','Dixon'),
        (randHash(8),'Adeline','Phillips'),
        (randHash(8),'Amy','Crawford'),
        (randHash(8),'Marc','Tate'),
        (randHash(8),'Brian','Bennett'),
        (randHash(8),'Della','Powers'),
        (randHash(8),'Nina','Ortiz'),
        (randHash(8),'Alex','Copeland'),
        (randHash(8),'Hulda','Lucas'),
        (randHash(8),'Herman','Griffith'),
        (randHash(8),'Leah','Lloyd'),
        (randHash(8),'Douglas','Mack'),
        (randHash(8),'Eunice','Morales'),
        (randHash(8),'Winnie','Taylor'),
        (randHash(8),'Lois','Ballard'),
        (randHash(8),'Clara','Harrison'),
        (randHash(8),'Amelia','Valdez'),
        (randHash(8),'Richard','Hodges'),
        (randHash(8),'Brandon','Schultz'),
        (randHash(8),'Jose','Hernandez'),
        (randHash(8),'Jim','Lucas'),
        (randHash(8),'Leon','Hudson'),
        (randHash(8),'Sara','Walters'),
        (randHash(8),'Victoria','Leonard'),
        (randHash(8),'Joseph','Wheeler'),
        (randHash(8),'Evelyn','Wheeler'),
        (randHash(8),'Allen','McCormick'),
        (randHash(8),'Grace','Aguilar'),
        (randHash(8),'Sylvia','Sparks'),
        (randHash(8),'Jordan','Ortiz'),
        (randHash(8),'Lucille','Gibbs'),
        (randHash(8),'Madge','Diaz'),
        (randHash(8),'Adrian','Taylor'),
        (randHash(8),'Tillie','Paul'),
        (randHash(8),'Eugenia','Daniels'),
        (randHash(8),'Alfred','Morrison'),
        (randHash(8),'Minerva','McCormick'),
        (randHash(8),'Isaiah','Garcia'),
        (randHash(8),'Francis','Jimenez'),
        (randHash(8),'Christina','Carlson'),
        (randHash(8),'Adam','Martin'),
        (randHash(8),'Raymond','Rice'),
        (randHash(8),'Nancy','Clayton'),
        (randHash(8),'Ronald','Horton'),
        (randHash(8),'Alvin','Allison'),
        (randHash(8),'Ralph','Harvey'),
        (randHash(8),'Eddie','Mendez'),
        (randHash(8),'Bess','Parker'),
        (randHash(8),'Owen','Rodriguez'),
        (randHash(8),'Victoria','King'),
        (randHash(8),'Isabel','Thomas'),
        (randHash(8),'William','Strickland'),
        (randHash(8),'Georgia','Powers'),
        (randHash(8),'Eva','Gomez'),
        (randHash(8),'Clifford','Garner'),
        (randHash(8),'Evelyn','Drake'),
        (randHash(8),'Scott','Briggs'),
        (randHash(8),'Sue','Owens'),
        (randHash(8),'Ethan','Flores'),
        (randHash(8),'Peter','McCormick'),
        (randHash(8),'George','Wright'),
        (randHash(8),'John','Christensen'),
        (randHash(8),'Luis','Atkins'),
        (randHash(8),'Hattie','Morales'),
        (randHash(8),'Brett','Brown'),
        (randHash(8),'Bernard','Fields'),
        (randHash(8),'Philip','Williamson'),
        (randHash(8),'Jon','Fields'),
        (randHash(8),'Adele','Roy'),
        (randHash(8),'Jonathan','Murray'),
        (randHash(8),'Jane','Adkins'),
        (randHash(8),'Juan','Flores'),
        (randHash(8),'Travis','Summers'),
        (randHash(8),'Gilbert','Carter'),
        (randHash(8),'Tony','Goodwin'),
        (randHash(8),'Mina','Cook'),
        (randHash(8),'Alexander','Quinn'),
        (randHash(8),'Derrick','Matthews'),
        (randHash(8),'Jay','Matthews'),
        (randHash(8),'Rosa','Christensen'),
        (randHash(8),'Henrietta','Haynes'),
        (randHash(8),'Danny','Bryan'),
        (randHash(8),'Gilbert','Guzman'),
        (randHash(8),'Ada','Alvarez'),
        (randHash(8),'Leila','Elliott'),
        (randHash(8),'Georgie','Silva'),
        (randHash(8),'Donald','Wise'),
        (randHash(8),'Cecelia','Miles'),
        (randHash(8),'Hallie','Todd'),
        (randHash(8),'Trevor','Graves'),
        (randHash(8),'Leah','Haynes'),
        (randHash(8),'Rena','Johnson'),
        (randHash(8),'Adam','Young'),
        (randHash(8),'Tom','Sandoval'),
        (randHash(8),'Edward','Morgan'),
        (randHash(8),'Andre','Bowman'),
        (randHash(8),'Edgar','Chambers'),
        (randHash(8),'Benjamin','Freeman'),
        (randHash(8),'Gilbert','Chavez'),
        (randHash(8),'Alma','Tate'),
        (randHash(8),'Eula','Kim'),
        (randHash(8),'Rodney','Franklin'),
        (randHash(8),'Clyde','Stanley'),
        (randHash(8),'Hunter','Bryan'),
        (randHash(8),'Isabel','Snyder'),
        (randHash(8),'Russell','Moran'),
        (randHash(8),'Louisa','Bates'),
        (randHash(8),'Violet','Vaughn'),
        (randHash(8),'Mable','Barnett'),
        (randHash(8),'Jon','Shelton'),
        (randHash(8),'Rodney','Hansen'),
        (randHash(8),'Thomas','McKenzie'),
        (randHash(8),'Isabel','Johnson'),
        (randHash(8),'Bobby','Campbell'),
        (randHash(8),'Jeff','Curtis'),
        (randHash(8),'Brent','Phelps'),
        (randHash(8),'Brandon','Phelps'),
        (randHash(8),'Eunice','Stokes'),
        (randHash(8),'Ryan','Austin'),
        (randHash(8),'Allie','Ortiz'),
        (randHash(8),'Isaac','Williamson'),
        (randHash(8),'Nannie','Brewer'),
        (randHash(8),'Jim','Gordon'),
        (randHash(8),'Sophie','Gross'),
        (randHash(8),'Harriet','Ward'),
        (randHash(8),'Nannie','Obrien'),
        (randHash(8),'Jesse','Hill'),
        (randHash(8),'Dollie','Hoffman'),
        (randHash(8),'Celia','Adkins'),
        (randHash(8),'Phillip','Henderson'),
        (randHash(8),'Eddie','Thompson'),
        (randHash(8),'Chad','Welch'),
        (randHash(8),'Adrian','Jordan'),
        (randHash(8),'Adele','Lamb'),
        (randHash(8),'Nancy','Becker'),
        (randHash(8),'Jordan','Hardy'),
        (randHash(8),'Mathilda','Washington'),
        (randHash(8),'Jacob','Evans'),
        (randHash(8),'Christian','Watts'),
        (randHash(8),'Dustin','Delgado'),
        (randHash(8),'Johnny','Manning'),
        (randHash(8),'Leroy','Moss'),
        (randHash(8),'Luke','Mendez'),
        (randHash(8),'Nora','Pope'),
        (randHash(8),'Isabel','Wright'),
        (randHash(8),'Craig','Simon'),
        (randHash(8),'Don','Scott'),
        (randHash(8),'Verna','Jones'),
        (randHash(8),'Olga','Kelley'),
        (randHash(8),'Leona','Schneider'),
        (randHash(8),'Nathaniel','Bass'),
        (randHash(8),'Alan','Garza'),
        (randHash(8),'Howard','Walker'),
        (randHash(8),'Patrick','Stewart'),
        (randHash(8),'Bertie','Rodriguez'),
        (randHash(8),'Roy','Andrews'),
        (randHash(8),'Hannah','Perkins'),
        (randHash(8),'Alta','Fields'),
        (randHash(8),'Della','Price'),
        (randHash(8),'Andrew','Stephens'),
        (randHash(8),'Virgie','Logan'),
        (randHash(8),'Peter','Stone'),
        (randHash(8),'Ronnie','Holloway'),
        (randHash(8),'Sally','Burke'),
        (randHash(8),'Chester','Hughes'),
        (randHash(8),'Tyler','Turner'),
        (randHash(8),'Mary','Moreno'),
        (randHash(8),'Nathan','Rodriguez'),
        (randHash(8),'Jordan','Thompson'),
        (randHash(8),'Paul','Perry'),
        (randHash(8),'Devin','Stewart'),
        (randHash(8),'Ronnie','Neal'),
        (randHash(8),'Ernest','Atkins'),
        (randHash(8),'Oscar','Cox'),
        (randHash(8),'Gilbert','Guzman'),
        (randHash(8),'Jeremy','Glover'),
        (randHash(8),'Pearl','Craig'),
        (randHash(8),'Logan','Carr'),
        (randHash(8),'Esther','Martinez'),
        (randHash(8),'Carlos','Douglas'),
        (randHash(8),'Barbara','Day'),
        (randHash(8),'Ada','Day'),
        (randHash(8),'Travis','Williams'),
        (randHash(8),'Lizzie','Reed'),
        (randHash(8),'Micheal','Manning'),
        (randHash(8),'Henry','Brady'),
        (randHash(8),'Lucinda','Douglas'),
        (randHash(8),'Harold','Wise'),
        (randHash(8),'Shane','Wheeler'),
        (randHash(8),'Bruce','Fletcher'),
        (randHash(8),'Tom','Harrington'),
        (randHash(8),'Allie','Phelps'),
        (randHash(8),'Ollie','Harper'),
        (randHash(8),'Nettie','Elliott'),
        (randHash(8),'Rena','Yates'),
        (randHash(8),'Richard','Hampton'),
        (randHash(8),'Jordan','Franklin'),
        (randHash(8),'Sue','Gibson'),
        (randHash(8),'Joseph','Goodwin'),
        (randHash(8),'Mark','Rose'),
        (randHash(8),'Connor','Norman'),
        (randHash(8),'Fannie','Strickland'),
        (randHash(8),'Lura','Daniel'),
        (randHash(8),'Jessie','Waters'),
        (randHash(8),'Sean','Morton'),
        (randHash(8),'Lelia','Owen'),
        (randHash(8),'Loretta','Fox'),
        (randHash(8),'Hallie','Herrera'),
        (randHash(8),'Ada','West'),
        (randHash(8),'Louise','Todd'),
        (randHash(8),'Marguerite','Reyes'),
        (randHash(8),'Sadie','Henry'),
        (randHash(8),'Lucinda','Briggs'),
        (randHash(8),'Ricky','Huff'),
        (randHash(8),'Sue','Curtis'),
        (randHash(8),'Lawrence','Copeland'),
        (randHash(8),'Nina','Harris'),
        (randHash(8),'Mason','Brown'),
        (randHash(8),'Willie','Poole'),
        (randHash(8),'Dora','Long'),
        (randHash(8),'Mario','Tran'),
        (randHash(8),'Gertrude','Oliver'),
        (randHash(8),'Patrick','Vasquez'),
        (randHash(8),'Myrtie','Ross'),
        (randHash(8),'Cory','Gross'),
        (randHash(8),'Phoebe','Mason'),
        (randHash(8),'Jared','Cannon'),
        (randHash(8),'Louise','Lucas'),
        (randHash(8),'Joe','James'),
        (randHash(8),'Lula','Francis'),
        (randHash(8),'Blake','Maxwell'),
        (randHash(8),'Inez','Roy'),
        (randHash(8),'Leah','James'),
        (randHash(8),'Wesley','Vaughn'),
        (randHash(8),'Minerva','Schultz'),
        (randHash(8),'Don','Williams'),
        (randHash(8),'Bill','Garza'),
        (randHash(8),'Larry','Bridges'),
        (randHash(8),'Gary','Stevens'),
        (randHash(8),'Steven','Francis'),
        (randHash(8),'Blanche','Reid'),
        (randHash(8),'Maud','Goodwin'),
        (randHash(8),'Jonathan','Cunningham'),
        (randHash(8),'Seth','French'),
        (randHash(8),'Jennie','Austin'),
        (randHash(8),'Harriet','Rivera'),
        (randHash(8),'Louis','Aguilar'),
        (randHash(8),'Kyle','Davis'),
        (randHash(8),'Lula','Miller'),
        (randHash(8),'Juan','Tyler'),
        (randHash(8),'Myra','Fowler'),
        (randHash(8),'Louisa','Briggs'),
        (randHash(8),'Elva','Coleman'),
        (randHash(8),'Raymond','McDonald'),
        (randHash(8),'Vincent','Campbell'),
        (randHash(8),'Garrett','Warner'),
        (randHash(8),'Essie','Cortez'),
        (randHash(8),'Sam','Graves'),
        (randHash(8),'Olivia','Douglas'),
        (randHash(8),'Inez','Casey'),
        (randHash(8),'Jordan','Sullivan'),
        (randHash(8),'Landon','Webster'),
        (randHash(8),'Gary','Sparks'),
        (randHash(8),'Marie','Walsh'),
        (randHash(8),'Ophelia','Benson'),
        (randHash(8),'Willie','Malone'),
        (randHash(8),'Blanche','Bailey'),
        (randHash(8),'Frederick','Clark'),
        (randHash(8),'Isabella','Mason'),
        (randHash(8),'Maria','Cook'),
        (randHash(8),'Clyde','Hamilton'),
        (randHash(8),'Lora','Daniel'),
        (randHash(8),'Hattie','Blake'),
        (randHash(8),'Jacob','Burgess'),
        (randHash(8),'Jerry','Jensen'),
        (randHash(8),'Phoebe','Long'),
        (randHash(8),'Micheal','Dennis'),
        (randHash(8),'Lelia','Douglas'),
        (randHash(8),'Jeff','Meyer'),
        (randHash(8),'Martha','Harvey'),
        (randHash(8),'William','Stewart'),
        (randHash(8),'Grace','Fletcher'),
        (randHash(8),'Bernard','Barnett'),
        (randHash(8),'Alan','McCarthy'),
        (randHash(8),'Sarah','Abbott'),
        (randHash(8),'Nathaniel','Price'),
        (randHash(8),'Chris','Jimenez'),
        (randHash(8),'Lela','Hammond'),
        (randHash(8),'Lydia','Erickson'),
        (randHash(8),'Chad','Carpenter'),
        (randHash(8),'Lucile','Weaver'),
        (randHash(8),'Edna','Allison'),
        (randHash(8),'Cole','Graham'),
        (randHash(8),'Kyle','Banks'),
        (randHash(8),'Matilda','Hubbard'),
        (randHash(8),'Eugene','Marshall'),
        (randHash(8),'Vernon','Watts'),
        (randHash(8),'Lenora','Manning'),
        (randHash(8),'Bryan','Morales'),
        (randHash(8),'Nathaniel','Osborne'),
        (randHash(8),'Lenora','Roberts'),
        (randHash(8),'Evan','Washington'),
        (randHash(8),'William','Chavez'),
        (randHash(8),'Minnie','Rose'),
        (randHash(8),'Clayton','Norris'),
        (randHash(8),'Frank','Freeman'),
        (randHash(8),'Dora','Walsh'),
        (randHash(8),'Jose','Moore'),
        (randHash(8),'Rosa','Martin'),
        (randHash(8),'Jason','Morales'),
        (randHash(8),'Roy','McKenzie'),
        (randHash(8),'Wesley','Schwartz'),
        (randHash(8),'James','Black'),
        (randHash(8),'Jeremy','Abbott'),
        (randHash(8),'Cordelia','Guerrero'),
        (randHash(8),'Derrick','Fitzgerald'),
        (randHash(8),'Larry','McLaughlin'),
        (randHash(8),'David','Curtis'),
        (randHash(8),'Steve','Walters'),
        (randHash(8),'Manuel','Valdez'),
        (randHash(8),'Carl','Vaughn'),
        (randHash(8),'Marcus','Hunt'),
        (randHash(8),'Cecilia','Graham'),
        (randHash(8),'Julia','Harrington'),
        (randHash(8),'Jimmy','Brooks'),
        (randHash(8),'Ida','King'),
        (randHash(8),'Dale','Graham'),
        (randHash(8),'Nathaniel','Ruiz'),
        (randHash(8),'Donald','Barrett'),
        (randHash(8),'Kyle','Jacobs'),
        (randHash(8),'Adelaide','Nguyen'),
        (randHash(8),'Lenora','Murphy'),
        (randHash(8),'Ray','Weaver'),
        (randHash(8),'Robert','McCarthy'),
        (randHash(8),'Leo','Quinn'),
        (randHash(8),'Jerome','Holt'),
        (randHash(8),'Cynthia','Aguilar'),
        (randHash(8),'Sue','Baker'),
        (randHash(8),'Bernard','Drake'),
        (randHash(8),'Albert','Diaz'),
        (randHash(8),'Gordon','Harrison'),
        (randHash(8),'Alfred','Robinson'),
        (randHash(8),'Susie','Martin'),
        (randHash(8),'Dustin','Pena'),
        (randHash(8),'Esther','Knight'),
        (randHash(8),'Mark','Webb'),
        (randHash(8),'Matthew','Boyd'),
        (randHash(8),'Adeline','Thomas'),
        (randHash(8),'Marie','Abbott'),
        (randHash(8),'Henry','Delgado'),
        (randHash(8),'Shawn','Lowe'),
        (randHash(8),'Catherine','Soto'),
        (randHash(8),'Chase','Miles'),
        (randHash(8),'Lucy','Fuller'),
        (randHash(8),'Jane','Tran'),
        (randHash(8),'Florence','Green'),
        (randHash(8),'Lilly','Thomas'),
        (randHash(8),'Travis','McCarthy'),
        (randHash(8),'Jean','Hodges'),
        (randHash(8),'Rebecca','Thompson'),
        (randHash(8),'Polly','Hammond'),
        (randHash(8),'Gussie','Webb'),
        (randHash(8),'Andre','Lee'),
        (randHash(8),'Russell','Cook'),
        (randHash(8),'Eunice','Padilla'),
        (randHash(8),'Herbert','Chavez'),
        (randHash(8),'Erik','Mack'),
        (randHash(8),'Brett','Wheeler'),
        (randHash(8),'Olive','Hudson'),
        (randHash(8),'Joshua','Zimmerman'),
        (randHash(8),'Anthony','Davidson'),
        (randHash(8),'Victor','Graham'),
        (randHash(8),'Sara','Gross'),
        (randHash(8),'Emily','Rose'),
        (randHash(8),'Celia','Hamilton'),
        (randHash(8),'Hunter','Doyle'),
        (randHash(8),'Agnes','Kelley'),
        (randHash(8),'Agnes','Scott'),
        (randHash(8),'Edward','Griffith'),
        (randHash(8),'Elizabeth','Ballard'),
        (randHash(8),'Nannie','Jackson'),
        (randHash(8),'Brandon','Fisher'),
        (randHash(8),'Mildred','Washington'),
        (randHash(8),'Frederick','Howard'),
        (randHash(8),'Winnie','Norman'),
        (randHash(8),'Earl','Higgins'),
        (randHash(8),'Nicholas','Gilbert'),
        (randHash(8),'Estelle','Sims'),
        (randHash(8),'John','Erickson'),
        (randHash(8),'Rodney','Gibbs'),
        (randHash(8),'Helen','Hanson'),
        (randHash(8),'Kenneth','Hart'),
        (randHash(8),'Henrietta','Klein'),
        (randHash(8),'Marion','May'),
        (randHash(8),'Russell','Washington'),
        (randHash(8),'Ina','Simpson'),
        (randHash(8),'Clifford','Kelley'),
        (randHash(8),'Mamie','Casey'),
        (randHash(8),'Leon','Allen'),
        (randHash(8),'Anne','Watson'),
        (randHash(8),'Elmer','Patterson'),
        (randHash(8),'Marian','Crawford'),
        (randHash(8),'Helen','Benson'),
        (randHash(8),'Wesley','Alvarado'),
        (randHash(8),'Norman','Potter'),
        (randHash(8),'Alvin','Simpson'),
        (randHash(8),'Winnie','Becker'),
        (randHash(8),'Marguerite','White'),
        (randHash(8),'Stephen','Castro'),
        (randHash(8),'Antonio','Sharp'),
        (randHash(8),'Alberta','Lindsey'),
        (randHash(8),'Charlotte','Padilla'),
        (randHash(8),'Miguel','Webster'),
        (randHash(8),'Ernest','Rios'),
        (randHash(8),'Jay','Lane'),
        (randHash(8),'Trevor','Alvarado'),
        (randHash(8),'Charlie','Young'),
        (randHash(8),'Gavin','Elliott'),
        (randHash(8),'Cody','Atkins'),
        (randHash(8),'Mario','Bass'),
        (randHash(8),'Ollie','Cunningham'),
        (randHash(8),'Claudia','Sanchez'),
        (randHash(8),'Anthony','Jenkins'),
        (randHash(8),'Albert','McLaughlin'),
        (randHash(8),'Walter','Sparks'),
        (randHash(8),'Elijah','Warren'),
        (randHash(8),'Lillian','Cunningham'),
        (randHash(8),'Mark','Massey'),
        (randHash(8),'Fannie','Collier'),
        (randHash(8),'Chad','Armstrong'),
        (randHash(8),'Edwin','Hopkins'),
        (randHash(8),'Jared','Barnett'),
        (randHash(8),'Ernest','Page'),
        (randHash(8),'Sara','Bryant'),
        (randHash(8),'Ernest','Coleman'),
        (randHash(8),'Ella','Morales'),
        (randHash(8),'Henry','Valdez'),
        (randHash(8),'Gary','Guzman'),
        (randHash(8),'Minerva','Lyons'),
        (randHash(8),'Anthony','Sutton'),
        (randHash(8),'Georgie','Richardson'),
        (randHash(8),'Theodore','Fernandez'),
        (randHash(8),'James','McCarthy'),
        (randHash(8),'Ann','Tyler'),
        (randHash(8),'Lewis','Carr'),
        (randHash(8),'Jeff','Rodriquez'),
        (randHash(8),'Susan','Aguilar'),
        (randHash(8),'Carolyn','Pratt'),
        (randHash(8),'Milton','Jimenez'),
        (randHash(8),'Miguel','Murray'),
        (randHash(8),'Darrell','Bryant'),
        (randHash(8),'Sam','Pierce'),
        (randHash(8),'Jerome','Lamb'),
        (randHash(8),'Della','Bryan'),
        (randHash(8),'Dylan','Rodriguez'),
        (randHash(8),'Sarah','Moreno'),
        (randHash(8),'Theodore','Becker'),
        (randHash(8),'Callie','Padilla'),
        (randHash(8),'Joseph','Copeland'),
        (randHash(8),'Franklin','Atkins'),
        (randHash(8),'Georgie','Hoffman'),
        (randHash(8),'Bettie','Nguyen'),
        (randHash(8),'Sarah','Norris'),
        (randHash(8),'Jackson','Moran'),
        (randHash(8),'Lenora','Cohen'),
        (randHash(8),'Craig','Keller'),
        (randHash(8),'Clara','Simmons'),
        (randHash(8),'Nannie','Curry'),
        (randHash(8),'Marcus','Ryan'),
        (randHash(8),'Erik','Bowman'),
        (randHash(8),'Charlotte','Newman'),
        (randHash(8),'Brian','Matthews'),
        (randHash(8),'Cameron','Romero'),
        (randHash(8),'Lucas','Warner'),
        (randHash(8),'Billy','Mendoza'),
        (randHash(8),'Kevin','Rowe'),
        (randHash(8),'Jackson','Chavez'),
        (randHash(8),'Marian','Perkins'),
        (randHash(8),'Emma','Lamb'),
        (randHash(8),'Justin','Rios'),
        (randHash(8),'Jeremiah','Brown'),
        (randHash(8),'Marcus','Gordon'),
        (randHash(8),'Adele','Snyder'),
        (randHash(8),'Noah','Reyes'),
        (randHash(8),'Charlie','Collier'),
        (randHash(8),'Mittie','Price'),
        (randHash(8),'Jackson','Wells'),
        (randHash(8),'Sylvia','Manning'),
        (randHash(8),'Katherine','Barber'),
        (randHash(8),'Eleanor','Snyder'),
        (randHash(8),'Chad','Vaughn'),
        (randHash(8),'Christina','Floyd'),
        (randHash(8),'Barbara','Wise'),
        (randHash(8),'Gussie','Butler'),
        (randHash(8),'Eddie','Ford'),
        (randHash(8),'Hannah','Fitzgerald'),
        (randHash(8),'Myrtle','Nunez'),
        (randHash(8),'Ophelia','Taylor'),
        (randHash(8),'Ronald','Hoffman'),
        (randHash(8),'Rodney','Bowen'),
        (randHash(8),'Mabel','Klein'),
        (randHash(8),'Lida','Hamilton'),
        (randHash(8),'Trevor','Farmer'),
        (randHash(8),'Julian','Rice'),
        (randHash(8),'Samuel','Hart'),
        (randHash(8),'Eugenia','Leonard'),
        (randHash(8),'Robert','Frank'),
        (randHash(8),'Florence','Wilson'),
        (randHash(8),'Eunice','Curtis'),
        (randHash(8),'Andre','White'),
        (randHash(8),'Harriett','Norman'),
        (randHash(8),'Lester','Murray'),
        (randHash(8),'Patrick','Higgins'),
        (randHash(8),'Dylan','Rose'),
        (randHash(8),'Isabella','Welch'),
        (randHash(8),'Tyler','Tucker'),
        (randHash(8),'Marguerite','Maxwell'),
        (randHash(8),'Allen','Frank'),
        (randHash(8),'Ruby','Porter'),
        (randHash(8),'Vincent','McLaughlin'),
        (randHash(8),'Travis','McDonald'),
        (randHash(8),'Lou','Weaver'),
        (randHash(8),'Edward','Richards'),
        (randHash(8),'Evelyn','Byrd'),
        (randHash(8),'Katharine','Clark'),
        (randHash(8),'Gregory','Wilson'),
        (randHash(8),'Julian','Gill'),
        (randHash(8),'Andre','Paul'),
        (randHash(8),'Tommy','Hawkins'),
        (randHash(8),'Hilda','Cortez'),
        (randHash(8),'Jean','Henderson'),
        (randHash(8),'Devin','Warren'),
        (randHash(8),'Gregory','Holmes'),
        (randHash(8),'Birdie','Moran'),
        (randHash(8),'Violet','Kennedy'),
        (randHash(8),'Julian','Allison'),
        (randHash(8),'Sophia','Phelps'),
        (randHash(8),'Albert','Norman'),
        (randHash(8),'Rachel','Freeman'),
        (randHash(8),'Albert','Johnson'),
        (randHash(8),'Garrett','Klein'),
        (randHash(8),'Derrick','Simon'),
        (randHash(8),'Gordon','Clarke'),
        (randHash(8),'Jeremiah','Holmes'),
        (randHash(8),'Evan','Coleman'),
        (randHash(8),'Lucille','Christensen'),
        (randHash(8),'Cory','Swanson'),
        (randHash(8),'Noah','Hardy'),
        (randHash(8),'Seth','Meyer'),
        (randHash(8),'Lily','Craig'),
        (randHash(8),'Paul','Guerrero'),
        (randHash(8),'Tony','Allison'),
        (randHash(8),'Violet','Zimmerman'),
        (randHash(8),'Lydia','Robertson'),
        (randHash(8),'Katharine','Howard'),
        (randHash(8),'Blanche','Freeman'),
        (randHash(8),'Vera','Hunt'),
        (randHash(8),'Jessie','Harrison'),
        (randHash(8),'Jeff','McGee'),
        (randHash(8),'Ophelia','Chapman'),
        (randHash(8),'Gregory','Hernandez'),
        (randHash(8),'Lilly','Casey'),
        (randHash(8),'Fannie','Myers'),
        (randHash(8),'Lora','Pearson'),
        (randHash(8),'Samuel','Henry'),
        (randHash(8),'Rosalie','Horton'),
        (randHash(8),'Mable','Nash'),
        (randHash(8),'Teresa','Holland'),
        (randHash(8),'Dylan','Burton'),
        (randHash(8),'Corey','Rodriguez'),
        (randHash(8),'Willie','Chapman'),
        (randHash(8),'Rose','Tate'),
        (randHash(8),'Brett','Farmer'),
        (randHash(8),'Myra','Kim'),
        (randHash(8),'Mabel','Klein'),
        (randHash(8),'Mathilda','Burns'),
        (randHash(8),'Helen','Floyd'),
        (randHash(8),'Josie','Perry'),
        (randHash(8),'Janie','Watkins'),
        (randHash(8),'Jayden','Cain'),
        (randHash(8),'Lester','Allison'),
        (randHash(8),'Callie','Chapman'),
        (randHash(8),'Ethan','Stokes'),
        (randHash(8),'Justin','Alvarado'),
        (randHash(8),'Vernon','Taylor'),
        (randHash(8),'Zachary','Freeman'),
        (randHash(8),'Chase','Snyder'),
        (randHash(8),'Inez','Stone'),
        (randHash(8),'Anthony','Chambers'),
        (randHash(8),'Edgar','Shelton'),
        (randHash(8),'Alex','Snyder'),
        (randHash(8),'Bradley','Murphy'),
        (randHash(8),'Bradley','Munoz'),
        (randHash(8),'Walter','Herrera'),
        (randHash(8),'Harvey','Guzman'),
        (randHash(8),'Callie','Joseph'),
        (randHash(8),'Bryan','Blake'),
        (randHash(8),'Albert','Robbins'),
        (randHash(8),'Johnny','Nichols'),
        (randHash(8),'Troy','Patton'),
        (randHash(8),'Della','Massey'),
        (randHash(8),'Jason','Bates'),
        (randHash(8),'Emma','Warren'),
        (randHash(8),'Willie','Wells'),
        (randHash(8),'Connor','Hogan'),
        (randHash(8),'Lizzie','Young'),
        (randHash(8),'Isaac','Newman'),
        (randHash(8),'Elizabeth','Schneider'),
        (randHash(8),'Michael','Moody'),
        (randHash(8),'Rosa','Blair'),
        (randHash(8),'Flora','Rodriquez'),
        (randHash(8),'Floyd','Burgess'),
        (randHash(8),'Sara','Bailey'),
        (randHash(8),'Norman','Alexander'),
        (randHash(8),'Max','Tyler'),
        (randHash(8),'Agnes','Jordan'),
        (randHash(8),'Leona','Hubbard'),
        (randHash(8),'Cory','Adams'),
        (randHash(8),'Alfred','Thornton'),
        (randHash(8),'Beulah','Benson'),
        (randHash(8),'Terry','Jenkins'),
        (randHash(8),'Eula','Torres'),
        (randHash(8),'Cory','Allen'),
        (randHash(8),'Mable','Patrick'),
        (randHash(8),'Erik','Steele'),
        (randHash(8),'Sophia','Wood'),
        (randHash(8),'Jason','Horton'),
        (randHash(8),'Justin','Dennis'),
        (randHash(8),'Tommy','Robinson'),
        (randHash(8),'Gene','Carr'),
        (randHash(8),'Georgie','Willis'),
        (randHash(8),'Joel','Stanley'),
        (randHash(8),'Albert','Lawson'),
        (randHash(8),'Ola','Fernandez'),
        (randHash(8),'Ella','Jordan'),
        (randHash(8),'Joel','Zimmerman'),
        (randHash(8),'Timothy','McDonald'),
        (randHash(8),'Alberta','Tyler'),
        (randHash(8),'Isabelle','Patton'),
        (randHash(8),'Ella','Rice'),
        (randHash(8),'Callie','Greene'),
        (randHash(8),'Rodney','Sanders'),
        (randHash(8),'Ralph','Leonard'),
        (randHash(8),'Isabel','Buchanan'),
        (randHash(8),'Francis','Bass'),
        (randHash(8),'Ann','Nelson'),
        (randHash(8),'Myrtie','Burgess'),
        (randHash(8),'Leo','Larson'),
        (randHash(8),'Fanny','Rodriquez'),
        (randHash(8),'Troy','Bryant'),
        (randHash(8),'Max','Fuller'),
        (randHash(8),'Calvin','Crawford'),
        (randHash(8),'Sean','Baldwin'),
        (randHash(8),'Marian','Silva'),
        (randHash(8),'Maud','Briggs'),
        (randHash(8),'Ronald','Graham'),
        (randHash(8),'Lola','Russell'),
        (randHash(8),'Jeremy','Morton'),
        (randHash(8),'Mable','Anderson'),
        (randHash(8),'Annie','Buchanan'),
        (randHash(8),'Leroy','Huff'),
        (randHash(8),'Frances','Cummings'),
        (randHash(8),'Garrett','Lowe'),
        (randHash(8),'Isabel','Holmes'),
        (randHash(8),'Lucille','Parks'),
        (randHash(8),'Miguel','Hunter'),
        (randHash(8),'Georgia','Flores'),
        (randHash(8),'Keith','Hammond'),
        (randHash(8),'Logan','Arnold'),
        (randHash(8),'Dollie','Estrada'),
        (randHash(8),'Alma','Goodwin'),
        (randHash(8),'Jack','Lee'),
        (randHash(8),'Mark','Haynes'),
        (randHash(8),'Vera','Adams'),
        (randHash(8),'Henrietta','Wilkerson'),
        (randHash(8),'Lula','Lloyd'),
        (randHash(8),'Katherine','Mathis'),
        (randHash(8),'Virginia','Marshall'),
        (randHash(8),'Jeff','Griffith'),
        (randHash(8),'Jeff','Blair'),
        (randHash(8),'Sallie','Little'),
        (randHash(8),'Genevieve','Marsh'),
        (randHash(8),'Calvin','Park'),
        (randHash(8),'Chase','Garrett'),
        (randHash(8),'Robert','Lopez'),
        (randHash(8),'Augusta','Gibson'),
        (randHash(8),'Eunice','Briggs'),
        (randHash(8),'Minnie','Harrington'),
        (randHash(8),'Christine','Lopez'),
        (randHash(8),'Jacob','Shelton'),
        (randHash(8),'Mason','Frazier'),
        (randHash(8),'Walter','Clayton'),
        (randHash(8),'Richard','Ramirez'),
        (randHash(8),'Samuel','Ross'),
        (randHash(8),'Bettie','Rodriquez'),
        (randHash(8),'Janie','Harvey'),
        (randHash(8),'Lillian','Price'),
        (randHash(8),'Harvey','McDaniel'),
        (randHash(8),'Arthur','Gordon'),
        (randHash(8),'Stanley','Bowers'),
        (randHash(8),'Belle','Woods'),
        (randHash(8),'Kathryn','Sanders'),
        (randHash(8),'May','Gray'),
        (randHash(8),'Mark','Lindsey'),
        (randHash(8),'Lizzie','Nunez'),
        (randHash(8),'Mildred','Ruiz'),
        (randHash(8),'Etta','Lane'),
        (randHash(8),'Rhoda','Hansen'),
        (randHash(8),'Steven','Martinez'),
        (randHash(8),'Susan','Saunders'),
        (randHash(8),'Essie','Santiago'),
        (randHash(8),'Edgar','Elliott'),
        (randHash(8),'Daisy','Norman'),
        (randHash(8),'Jose','Brewer'),
        (randHash(8),'Abbie','Cohen'),
        (randHash(8),'Delia','Castillo'),
        (randHash(8),'Ronald','Chandler'),
        (randHash(8),'Joshua','Miller'),
        (randHash(8),'Max','Cain'),
        (randHash(8),'Frederick','McDonald'),
        (randHash(8),'James','Shelton'),
        (randHash(8),'Matilda','Dawson'),
        (randHash(8),'Marvin','Pittman'),
        (randHash(8),'Corey','Gonzalez'),
        (randHash(8),'Andre','Mendoza'),
        (randHash(8),'Marcus','Fields'),
        (randHash(8),'Victoria','Sanchez'),
        (randHash(8),'Fred','Morton'),
        (randHash(8),'Kyle','Houston'),
        (randHash(8),'Dennis','Ray'),
        (randHash(8),'Jeremy','Hudson'),
        (randHash(8),'Clyde','Brady'),
        (randHash(8),'Mildred','Baldwin'),
        (randHash(8),'Elmer','Harvey'),
        (randHash(8),'Stanley','Tucker'),
        (randHash(8),'Lettie','Lopez'),
        (randHash(8),'Adelaide','Casey'),
        (randHash(8),'Victor','Thomas'),
        (randHash(8),'Alta','Garrett'),
        (randHash(8),'Jimmy','Ortiz'),
        (randHash(8),'Leonard','Robinson'),
        (randHash(8),'Vernon','Coleman'),
        (randHash(8),'Peter','Hart'),
        (randHash(8),'Alberta','Moran'),
        (randHash(8),'Pauline','Harmon'),
        (randHash(8),'Rena','Owens'),
        (randHash(8),'Miguel','Buchanan'),
        (randHash(8),'Bruce','Parker'),
        (randHash(8),'Wayne','Erickson'),
        (randHash(8),'Nell','Fleming'),
        (randHash(8),'Randy','Wilson'),
        (randHash(8),'Earl','Bowers'),
        (randHash(8),'Nora','Parker'),
        (randHash(8),'Gary','Medina'),
        (randHash(8),'Curtis','Kennedy'),
        (randHash(8),'Logan','Ball'),
        (randHash(8),'Dennis','Daniels'),
        (randHash(8),'Warren','Webster'),
        (randHash(8),'Lewis','Richardson'),
        (randHash(8),'Jeffrey','Kelley'),
        (randHash(8),'Jennie','Black'),
        (randHash(8),'Lela','Bates'),
        (randHash(8),'Gertrude','Mason'),
        (randHash(8),'Minnie','James'),
        (randHash(8),'Chad','Long'),
        (randHash(8),'Shane','Frazier'),
        (randHash(8),'Alejandro','Tucker'),
        (randHash(8),'Calvin','Howell'),
        (randHash(8),'Roxie','Chandler'),
        (randHash(8),'Lily','Hampton'),
        (randHash(8),'Mabel','Norton'),
        (randHash(8),'Florence','Perkins'),
        (randHash(8),'Lola','Douglas'),
        (randHash(8),'Eleanor','Griffith'),
        (randHash(8),'Luis','Hines'),
        (randHash(8),'Ricardo','Ramsey'),
        (randHash(8),'Alfred','Kennedy'),
        (randHash(8),'Kate','Cain'),
        (randHash(8),'Elmer','Gill'),
        (randHash(8),'Agnes','Howell'),
        (randHash(8),'Milton','Powell'),
        (randHash(8),'Cody','Griffith'),
        (randHash(8),'Jason','Daniels'),
        (randHash(8),'Gregory','Parsons'),
        (randHash(8),'Nell','Robertson'),
        (randHash(8),'Nannie','Rhodes'),
        (randHash(8),'Edgar','Barber'),
        (randHash(8),'Bertie','Fox'),
        (randHash(8),'Dorothy','Porter'),
        (randHash(8),'Cornelia','Patrick'),
        (randHash(8),'Linnie','Chandler'),
        (randHash(8),'Gussie','Porter'),
        (randHash(8),'Elizabeth','Clark'),
        (randHash(8),'Brett','Griffin'),
        (randHash(8),'Jerry','Berry'),
        (randHash(8),'Lawrence','Gibbs'),
        (randHash(8),'Jon','Lewis'),
        (randHash(8),'Celia','Duncan'),
        (randHash(8),'Chester','Chandler'),
        (randHash(8),'Jessie','Cole'),
        (randHash(8),'Matilda','Morgan'),
        (randHash(8),'Lela','Frank'),
        (randHash(8),'Alta','Gross'),
        (randHash(8),'Katharine','Davis'),
        (randHash(8),'Marian','Conner'),
        (randHash(8),'Marie','Curtis'),
        (randHash(8),'Nicholas','Powers'),
        (randHash(8),'Luella','Wong'),
        (randHash(8),'Ollie','Glover'),
        (randHash(8),'Maria','Christensen'),
        (randHash(8),'Effie','Mitchell'),
        (randHash(8),'Edith','Garrett'),
        (randHash(8),'Claudia','Hayes'),
        (randHash(8),'Tillie','Henderson'),
        (randHash(8),'Gordon','Banks'),
        (randHash(8),'Emily','McDonald'),
        (randHash(8),'Sam','Coleman'),
        (randHash(8),'Rena','Weber'),
        (randHash(8),'Julia','Webster'),
        (randHash(8),'Isabelle','Gill'),
        (randHash(8),'Don','Glover'),
        (randHash(8),'Justin','Fowler'),
        (randHash(8),'Lulu','Owens'),
        (randHash(8),'Georgie','Bowers'),
        (randHash(8),'Derek','Parks'),
        (randHash(8),'Celia','Aguilar'),
        (randHash(8),'Elizabeth','Thornton'),
        (randHash(8),'Ollie','Wise'),
        (randHash(8),'Elva','Ford'),
        (randHash(8),'Lucas','Newman'),
        (randHash(8),'Roy','Perkins'),
        (randHash(8),'Nellie','Park'),
        (randHash(8),'Myrtie','Jensen'),
        (randHash(8),'Daisy','Caldwell'),
        (randHash(8),'Jon','Wells'),
        (randHash(8),'Vincent','Brewer'),
        (randHash(8),'Gilbert','Robertson'),
        (randHash(8),'Jean','Marsh'),
        (randHash(8),'Lettie','Hicks'),
        (randHash(8),'Ophelia','Simpson'),
        (randHash(8),'Ethel','Hayes'),
        (randHash(8),'Bernice','Parker'),
        (randHash(8),'Maggie','Simmons');
 









/*----------------------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------- INSERT Building Type DATA ------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
INSERT INTO Building_Type(type_name)
  VALUES  ('Academic'),
          ('Fitness'),
          ('Health');
 










/*----------------------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------- INSERT BUILDING DATA -----------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('HEC', (SELECT id FROM Building_Type WHERE type_name='Academic' ), 'Harris Engineering', 300);
INSERT INTO Academic(building_code, coordinator_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='HEC'), 'Douglas Adams');

INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('CLR1', (SELECT id FROM Building_Type WHERE type_name='Academic' ), 'Classroom Building 1', 300);
INSERT INTO Academic(building_code, coordinator_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='CLR1'), 'Jerry Sinfeld');

INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('EGN', (SELECT id FROM Building_Type WHERE type_name='Academic' ), 'Engineering', 300);
INSERT INTO Academic(building_code, coordinator_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='EGN'), 'Billy Madison');
 
INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('HLT', (SELECT id FROM Building_Type WHERE type_name='Health' ), 'Pharmacy', 300);
INSERT INTO Health(building_code, doctor_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='HLT'), 'Dr. Johnson');
 
INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('GYM', (SELECT id FROM Building_Type WHERE type_name='Fitness' ), 'UCF Gym', 3000);
INSERT INTO Fitness(building_code, organizer_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='GYM'), 'Billy Bob');

INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('ER', (SELECT id FROM Building_Type WHERE type_name='Health' ), 'Emergency Room', 300);
INSERT INTO Health(building_code, doctor_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='ER'), 'Dr. Bradely');

INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('POL', (SELECT id FROM Building_Type WHERE type_name='Fitness' ), 'Swimming Pool', 3000);
INSERT INTO Fitness(building_code, organizer_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='POL'), 'James Buchannon');

INSERT INTO Building(building_code, building_type, building_name, human_capacity) 
    VALUES ('RBL', (SELECT id FROM Building_Type WHERE type_name='Fitness' ), 'Racquetball Court', 3000);
INSERT INTO Fitness(building_code, organizer_name)
    VALUES ((SELECT building_code FROM Building WHERE building_code='RBL'), 'Matthew Goddard');
 
           


/*----------------------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------ INSERT Resource DATA ------------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
INSERT INTO Resource(resource_name, student_capacity)
    VALUES      ('Chair', 5),
                ('Bench Press', 157),
                ('Chairs', 23),
                ('Bench Press', 139),
                ('Desk', 18),
                ('Desk', 160),
                ('MRI Machine', 92),
                ('Chairs', 77),
                ('Bench Press', 37),
                ('Desk', 78),
                ('X-Ray Machine', 75),
                ('Desk', 108),
                ('Desk', 22),
                ('Chairs', 191),
                ('Bench Press', 121),
                ('Chairs', 23),
                ('X-Ray Machine', 165),
                ('X-Ray Machine', 189),
                ('Bench Press', 115),
                ('Bench Press', 31),
                ('Chairs', 41),
                ('Desk', 22),
                ('Chairs', 143),
                ('X-Ray Machine', 135),
                ('MRI Machine', 140),
                ('Desk', 114),
                ('Bench Press', 187),
                ('X-Ray Machine', 153),
                ('Chairs', 83),
                ('Chairs', 41),
                ('X-Ray Machine', 63),
                ('Chairs', 179),
                ('X-Ray Machine', 57),
                ('Bench Press', 31),
                ('Desk', 126),
                ('Chairs', 71),
                ('X-Ray Machine', 51),
                ('X-Ray Machine', 87),
                ('X-Ray Machine', 123),
                ('X-Ray Machine', 147),
                ('Chairs', 107),
                ('X-Ray Machine', 69),
                ('Desk', 138),
                ('Bench Press', 73),
                ('MRI Machine', 110),
                ('Chairs', 17),
                ('Bench Press', 37),
                ('X-Ray Machine', 111),
                ('Desk', 108),
                ('X-Ray Machine', 105),
                ('MRI Machine', 134),
                ('MRI Machine', 92),
                ('Bench Press', 79),
                ('Desk', 58),
                ('MRI Machine', 86),
                ('Desk', 162),
                ('Desk', 124),
                ('MRI Machine', 86),
                ('Desk', 132),
                ('Desk', 60),
                ('Chairs', 5),
                ('Desk', 94),
                ('Desk', 64);


/*----------------------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------- INSERT Building_Resource DATA --------------------------------------------------------*/
/*----------------------------------------------------------------------------------------------------------------------------------*/
INSERT INTO Building_Resource(resource_id, building_code)    
  VALUES ((SELECT resource_id FROM Resource WHERE Resource.resource_name='MRI Machine' LIMIT 1),
          (SELECT building_code FROM Health NATURAL JOIN Building WHERE building_name='Pharmacy' LIMIT 1));
          
INSERT INTO Building_Resource(resource_id, building_code)    
  VALUES ((SELECT resource_id FROM Resource WHERE Resource.resource_name='Desk' LIMIT 1),
          (SELECT building_code FROM Academic NATURAL JOIN Building WHERE building_name='Harris Engineering'));          
          
INSERT INTO Building_Resource(resource_id, building_code)       
  VALUES ((SELECT resource_id FROM Resource WHERE Resource.resource_name='Chairs' LIMIT 1),           
          (SELECT building_code FROM Academic NATURAL JOIN Building WHERE building_name='Harris Engineering'));
        
INSERT INTO Building_Resource(resource_id, building_code)       
  VALUES ((SELECT resource_id FROM Resource WHERE Resource.resource_name='X-Ray Machine' LIMIT 1),           
          (SELECT building_code FROM Health NATURAL JOIN Building WHERE building_name='Pharmacy' LIMIT 1));
  












CALL UsageRecLoop(5000);
